# Generated by Django 6.0.6 on 2026-06-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ibge', models.IntegerField(unique=True)),
                ('sigla', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
