# Generated by Django 6.0.6 on 2026-06-13 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='id_ibge',
        ),
        migrations.AddField(
            model_name='estado',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estado',
            name='regiao',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estado',
            name='sigla',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
