# Generated by Django 6.0.6 on 2026-06-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0005_alter_municipio_options_municipio_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['nome'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AddField(
            model_name='estado',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='ibge_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='estado',
            name='regiao',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
