# Generated by Django 6.0.6 on 2026-06-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0006_alter_estado_options_estado_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='mesorregiao_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='mesorregiao_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
