# Generated by Django 6.0.6 on 2026-06-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0007_alter_municipio_mesorregiao_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='microrregiao_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='microrregiao_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
