# Generated by Django 6.0.6 on 2026-06-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0008_alter_municipio_microrregiao_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='mesorregiao_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='microrregiao_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='regiao',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='regiao_imediata_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='regiao_imediata_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='regiao_intermediaria_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='regiao_intermediaria_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
