# Generated by Django 6.0.6 on 2026-06-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0010_alter_municipio_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIBMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pibs', to='ibge.municipio')),
            ],
            options={
                'ordering': ['municipio', '-ano'],
                'constraints': [models.UniqueConstraint(fields=('municipio', 'ano'), name='unique_pib_municipio_ano')],
            },
        ),
    ]
