# Generated by Django 6.0.6 on 2026-06-16 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0011_pibmunicipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(db_index=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='ibge.indicador')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='ibge.municipio')),
            ],
            options={
                'ordering': ['municipio', 'indicador', '-ano'],
                'indexes': [models.Index(fields=['indicador', 'ano'], name='ibge_indica_indicad_c89b2d_idx'), models.Index(fields=['municipio', 'indicador'], name='ibge_indica_municip_7f9412_idx')],
                'constraints': [models.UniqueConstraint(fields=('municipio', 'indicador', 'ano'), name='uniq_indicador_municipio_ano')],
            },
        ),
    ]
