# Generated by Django 6.0.6 on 2026-06-13 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulacaoMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('populacao', models.BigIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populacoes', to='ibge.municipio')),
            ],
            options={
                'ordering': ['municipio', '-ano'],
                'unique_together': {('municipio', 'ano')},
            },
        ),
    ]
