# Generated by Django 6.0.6 on 2026-06-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0002_populacaomunicipio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='populacaomunicipio',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='populacaomunicipio',
            constraint=models.UniqueConstraint(fields=('municipio', 'ano'), name='unique_populacao_municipio_ano'),
        ),
    ]
