# Generated by Django 6.0.6 on 2026-06-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0003_alter_populacaomunicipio_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='codigo_externo',
            new_name='ibge_id',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='codigo_externo',
            new_name='ibge_id',
        ),
    ]
