# Generated by Django 6.0.6 on 2026-06-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0004_rename_codigo_externo_estado_ibge_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['nome'], 'verbose_name': 'Município', 'verbose_name_plural': 'Municípios'},
        ),
        migrations.AddField(
            model_name='municipio',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='mesorregiao_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='mesorregiao_nome',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='microrregiao_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='microrregiao_nome',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='regiao',
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='regiao_imediata_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='regiao_imediata_nome',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='regiao_intermediaria_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='regiao_intermediaria_nome',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='municipio',
            name='ibge_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nome',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
