# Generated by Django 6.0.6 on 2026-06-16 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0009_alter_municipio_mesorregiao_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='ibge.estado'),
        ),
    ]
