# Generated by Django 6.0.6 on 2026-06-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0012_indicador_indicadormunicipio'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pibmunicipio',
            name='unique_pib_municipio_ano',
        ),
        migrations.RemoveConstraint(
            model_name='populacaomunicipio',
            name='unique_populacao_municipio_ano',
        ),
        migrations.RemoveField(
            model_name='populacaomunicipio',
            name='municipio',
        ),
        migrations.DeleteModel(
            name='PIBMunicipio',
        ),
        migrations.DeleteModel(
            name='PopulacaoMunicipio',
        ),
    ]
