# Generated by Django 6.0.6 on 2026-07-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ibge", "0018_remove_indicador_municipio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indicador",
            options={
                "ordering": ["nome"],
                "verbose_name": "Indicador",
                "verbose_name_plural": "Indicadores",
            },
        ),
        migrations.RenameIndex(
            model_name="fatoindicador",
            new_name="ibge_fatoin_indicad_4bffb0_idx",
            old_name="ibge_fato_indicador_indicador_tempo_idx",
        ),
        migrations.RenameIndex(
            model_name="fatoindicador",
            new_name="ibge_fatoin_municip_6005e2_idx",
            old_name="ibge_fato_indicador_municipio_indicador_idx",
        ),
        migrations.RenameIndex(
            model_name="fatoindicador",
            new_name="ibge_fatoin_municip_ff5628_idx",
            old_name="ibge_fato_indicador_municipio_tempo_idx",
        ),
    ]
